name: Renovate
on:
  schedule:
    - cron: '0 20 * * *'
  
  workflow_dispatch:
  
  # Rebase open PRs on push
  push:
    branches: [ main ]
    
  pull_request:
    types: [synchronize, opened, reopened]
    paths:
      - .github/workflows/renovate.yaml
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@316d7cd859606d6039a2182b7d69199e9b036835 # v46.2.1
        with:
          configurationFile: .github/renovate.json5
          # https://docs.renovatebot.com/modules/platform/github/#running-using-a-fine-grained-token
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
            RENOVATE_REPOSITORIES: ${{ github.repository }}
            LOG_LEVEL: ${{ inputs.logLevel || 'debug' }}
