name: Renovate
on:
  schedule:
    - cron: '0 20 * * *'
  
  workflow_dispatch:
  
  # Rebase open PRs on push
  push:
    branches: [ main ]
    
  pull_request:
    types: [synchronize, opened, reopened]
    paths:
      - .github/workflows/renovate.yaml
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@79dc0ba74dc3de28db0a7aeb1d0b95d5bf5fde2a # v46.1.13
        with:
          configurationFile: .github/renovate.json5
          # https://docs.renovatebot.com/modules/platform/github/#running-using-a-fine-grained-token
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
            RENOVATE_REPOSITORIES: ${{ github.repository }}
            LOG_LEVEL: ${{ inputs.logLevel || 'debug' }}
